In [1]:
import numpy as np
from numpy import linalg as la

# Step 1

In [2]:
X = np.array([2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 2, 1, 1.5, 1.1])
y = np.array([2.4, 0.7, 2.9, 2.2, 3, 2.7, 1.6, 1.1, 1.6, 0.9])
data = np.array([X, y])
print(X)
print(y)
print(X.shape)
print(y.shape)

[2.5 0.5 2.2 1.9 3.1 2.3 2.  1.  1.5 1.1]
[2.4 0.7 2.9 2.2 3.  2.7 1.6 1.1 1.6 0.9]
(10,)
(10,)


In [3]:
xMean = np.mean(X)
yMean = np.mean(y)
print(xMean, yMean)

1.81 1.9100000000000001


In [4]:
data.shape

(2, 10)

# Step 2

In [6]:
meanAdjusted = np.zeros(data.shape)

for i in range (len(data[0])) :
    meanAdjusted[0][i] = data[0][i] - xMean
    
for i in range (len(data[1])) :
    meanAdjusted[1][i] = data[1][i] - yMean
    
print(meanAdjusted)

[[ 0.69 -1.31  0.39  0.09  1.29  0.49  0.19 -0.81 -0.31 -0.71]
 [ 0.49 -1.21  0.99  0.29  1.09  0.79 -0.31 -0.81 -0.31 -1.01]]


# Covariance Matrix

In [7]:
cov_mat = np.cov(data)
print(cov_mat)

[[0.61655556 0.61544444]
 [0.61544444 0.71655556]]


# Step 3

## Eigen Values and Eigen Vector

In [8]:
eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print("EigenValues\n", eig_vals)
print("EigenVectors\n", eig_vecs)

EigenValues
 [0.0490834  1.28402771]
EigenVectors
 [[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]]


# Step 4 
## Arrange Eigen Values in descending order and print also

In [10]:
#make list of tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:, i]) for i in range(len(eig_vals))]
print(eig_pairs)

#Sort tuples from high to low
eig_pairs.sort()
eig_pairs.reverse() #descending

print("Eigen VAlues in descsending order: ")
for i in eig_pairs:
    print(i[0])

[(0.04908339893832736, array([-0.73517866,  0.6778734 ])), (1.2840277121727837, array([-0.6778734 , -0.73517866]))]
Eigen VAlues in descsending order: 
1.2840277121727837
0.04908339893832736


In [11]:
print("Eigen Vectors in descending order: ")
for i in eig_pairs:
    print(i[1])

Eigen Vectors in descending order: 
[-0.6778734  -0.73517866]
[-0.73517866  0.6778734 ]


In [12]:
eig_pairs[0][1]

array([-0.6778734 , -0.73517866])

# Step 5

In [14]:
transformed_data1 = np.matmul(meanAdjusted.T, eig_pairs[0][1])
transformed_data1

array([-0.82797019,  1.77758033, -0.99219749, -0.27421042, -1.67580142,
       -0.9129491 ,  0.09910944,  1.14457216,  0.43804614,  1.22382056])

In [15]:
transformed_data2 = np.matmul(meanAdjusted.T, eig_pairs[1][1])
transformed_data2

array([-0.17511531,  0.14285723,  0.38437499,  0.13041721, -0.20949846,
        0.17528244, -0.3498247 ,  0.04641726,  0.01776463, -0.16267529])

In [16]:
transformed_data = [transformed_data1, transformed_data2]
transformed_data = np.transpose(transformed_data)
transformed_data

array([[-0.82797019, -0.17511531],
       [ 1.77758033,  0.14285723],
       [-0.99219749,  0.38437499],
       [-0.27421042,  0.13041721],
       [-1.67580142, -0.20949846],
       [-0.9129491 ,  0.17528244],
       [ 0.09910944, -0.3498247 ],
       [ 1.14457216,  0.04641726],
       [ 0.43804614,  0.01776463],
       [ 1.22382056, -0.16267529]])

In [17]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(2, 1), eig_pairs[1][1].reshape(2, 1)))
matrix_w

array([[-0.6778734 , -0.73517866],
       [-0.73517866,  0.6778734 ]])

# Step 6

## (Sanjana has not done but this has to be done Kyu woh Phone pe bolta hun)

In [18]:
original_data = np.matmul(transformed_data, matrix_w)
original_data[:][:] = original_data[:][:] + [xMean, yMean]
original_data

array([[2.5, 2.4],
       [0.5, 0.7],
       [2.2, 2.9],
       [1.9, 2.2],
       [3.1, 3. ],
       [2.3, 2.7],
       [2. , 1.6],
       [1. , 1.1],
       [1.5, 1.6],
       [1.1, 0.9]])

# for any changes change only X and y